# Generated by Django 2.2 on 2020-06-03 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StudyBlog_admin', '0006_profile_kurs'),
    ]

    operations = [
        migrations.AddField(
            model_name='kurs',
            name='teacher_link',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kurs', to='StudyBlog_admin.teacher', verbose_name='какой учитель'),
        ),
    ]
