# Generated by Django 2.2 on 2020-06-20 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudyBlog_admin', '0010_subscribe_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribe_course',
            name='text_email',
            field=models.TextField(blank=True, default='', max_length=1048, null=True, verbose_name='текст рассылки'),
        ),
    ]
