# Generated by Django 2.2 on 2020-06-21 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudyBlog_admin', '0011_subscribe_course_text_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribe_course',
            name='id_student',
            field=models.CharField(blank=True, default='', max_length=264, null=True, verbose_name='id студента'),
        ),
    ]
