# Generated by Django 2.2 on 2020-06-24 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudyBlog_admin', '0013_subscribe_course_id_kurs'),
    ]

    operations = [
        migrations.CreateModel(
            name='text_msg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, default='None', max_length=4096, null=True, verbose_name=' текст для отправки ')),
                ('is_active', models.BooleanField(default='False', null=True, verbose_name='включить эту рассылку, внимание включить можно только одну рассылку ')),
            ],
            options={
                'verbose_name': 'Текст для рассылки',
                'verbose_name_plural': 'Текст для рассылки',
            },
        ),
        migrations.AlterField(
            model_name='subscribe_course',
            name='is_active',
            field=models.BooleanField(default='False', verbose_name='добавление в рассылку'),
        ),
    ]
