# Generated by Django 2.2 on 2020-06-28 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StudyBlog_admin', '0015_auto_20200627_2042'),
    ]

    operations = [
        migrations.CreateModel(
            name='name_pol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, default='None', max_length=32, null=True, verbose_name='пол')),
            ],
            options={
                'verbose_name': 'пол',
                'verbose_name_plural': 'пол',
            },
        ),
        migrations.AlterModelOptions(
            name='text_msg',
            options={'verbose_name': 'Задачю для рассылки', 'verbose_name_plural': 'Задачи для рассылки'},
        ),
        migrations.AlterField(
            model_name='text_msg',
            name='link',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item', to='StudyBlog_admin.name_kurs', verbose_name='имя курса в которые вы хотите добавить сообщения'),
        ),
        migrations.AlterField(
            model_name='text_msg',
            name='name',
            field=models.TextField(blank=True, default='', max_length=4096, null=True, verbose_name=' текст для отправки '),
        ),
    ]
