# Generated by Django 2.2 on 2020-06-28 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StudyBlog_admin', '0016_auto_20200628_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='text_msg',
            name='link_pol',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item', to='StudyBlog_admin.name_pol', verbose_name='pol'),
        ),
        migrations.AlterField(
            model_name='name_pol',
            name='name',
            field=models.TextField(blank=True, default='', max_length=32, null=True, verbose_name='пол'),
        ),
    ]
