# Generated by Django 2.2 on 2020-06-28 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StudyBlog_admin', '0019_auto_20200628_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text_msg',
            name='link_pol',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item', to='StudyBlog_admin.name_pol', verbose_name='пол'),
        ),
    ]
