# Generated by Django 2.2.13 on 2020-07-08 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudyBlog_admin', '0020_auto_20200628_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='day_event',
            name='is_active',
            field=models.BooleanField(default='True', verbose_name='активно'),
        ),
        migrations.AlterField(
            model_name='kurs',
            name='is_active',
            field=models.BooleanField(default='True', verbose_name='курс активен'),
        ),
    ]
