# Generated by Django 2.2.13 on 2020-07-27 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudyBlog_admin', '0021_auto_20200708_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_verifecieted',
            field=models.BooleanField(default='False', verbose_name='профиль прошел верификацию'),
        ),
    ]
